language: rust
rust:
  - nightly

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake

before_script:
  - cargo install --git https://github.com/roblabla/cargo-travis --branch cargo-metadata

after_success:
  - cargo coveralls -v